--
-- PostgreSQL database dump
--

-- Dumped from database version 13.4
-- Dumped by pg_dump version 13.4

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bank_account; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bank_account (
    bank_account_id integer NOT NULL,
    card_number character varying(255),
    expiration_date character varying(255),
    first_name character varying(255),
    last_name character varying(255),
    pin_number integer,
    card_type_id integer NOT NULL,
    account_balance double precision,
    active boolean
);


ALTER TABLE public.bank_account OWNER TO postgres;

--
-- Name: bank_account_bank_account_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.bank_account ALTER COLUMN bank_account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bank_account_bank_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: card_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.card_type (
    card_type_id integer NOT NULL,
    card_type_name character varying(255)
);


ALTER TABLE public.card_type OWNER TO postgres;

--
-- Name: card_type_card_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.card_type ALTER COLUMN card_type_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.card_type_card_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: transaction; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transaction (
    transaction_id integer NOT NULL,
    amount double precision,
    "time" timestamp without time zone,
    bank_account_id integer
);


ALTER TABLE public.transaction OWNER TO postgres;

--
-- Name: transaction_transaction_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.transaction ALTER COLUMN transaction_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.transaction_transaction_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_person; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.user_person (
    user_id bigint NOT NULL,
    username character varying,
    password character varying
);


ALTER TABLE public.user_person OWNER TO postgres;

--
-- Data for Name: bank_account; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.bank_account (bank_account_id, card_number, expiration_date, first_name, last_name, pin_number, card_type_id, account_balance, active) FROM stdin;
1	123412341234	11/22	Marko	Markovic	1234	1	960	f
2	123456789	11/22	Djordje	Cvijic	1234	1	1608	t
\.


--
-- Data for Name: card_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.card_type (card_type_id, card_type_name) FROM stdin;
1	VISA
2	MASTERCARD
3	AMERICAN EXPRESS
\.


--
-- Data for Name: transaction; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.transaction (transaction_id, amount, "time", bank_account_id) FROM stdin;
1	36	2022-04-16 16:17:26.334726	1
2	40	2022-04-16 16:17:26.334726	2
3	52	2022-04-18 11:52:55.112474	2
4	56	2022-04-18 11:55:14.504062	2
5	60	2022-05-24 15:38:46.529007	2
6	60	2022-05-24 15:43:48.62019	2
7	64	2022-05-24 16:03:41.494434	2
8	64	2022-05-24 16:04:41.571084	2
\.


--
-- Data for Name: user_person; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.user_person (user_id, username, password) FROM stdin;
1	admin	JAvlGPq9JyTdtvBO6x2llnRI1+gxwIyPqCKAn3THIKk=
\.


--
-- Name: bank_account_bank_account_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.bank_account_bank_account_id_seq', 2, true);


--
-- Name: card_type_card_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.card_type_card_type_id_seq', 3, true);


--
-- Name: transaction_transaction_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.transaction_transaction_id_seq', 8, true);


--
-- Name: bank_account bank_account_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bank_account
    ADD CONSTRAINT bank_account_pkey PRIMARY KEY (bank_account_id);


--
-- Name: card_type card_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.card_type
    ADD CONSTRAINT card_type_pkey PRIMARY KEY (card_type_id);


--
-- Name: transaction transaction_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT transaction_pkey PRIMARY KEY (transaction_id);


--
-- Name: user_person user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.user_person
    ADD CONSTRAINT user_pkey PRIMARY KEY (user_id);


--
-- Name: transaction fkec44dj1u86xnsku7ld84pirje; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transaction
    ADD CONSTRAINT fkec44dj1u86xnsku7ld84pirje FOREIGN KEY (bank_account_id) REFERENCES public.bank_account(bank_account_id);


--
-- Name: bank_account fkn80utyv3318a1tjckjas3sspt; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bank_account
    ADD CONSTRAINT fkn80utyv3318a1tjckjas3sspt FOREIGN KEY (card_type_id) REFERENCES public.card_type(card_type_id);


--
-- PostgreSQL database dump complete
--

